PREFIX : <http://pros.upv.es/pvalderas/IoTDevices>
PREFIX sosa: <http://www.w3.org/ns/sosa/> 
ASK { 
	?s a :PresenceDectector . 
	?o a sosa:Observation . 
	?s sosa:madeObservation ?o . 
	?o sosa:hasResult ?result . 
	?o sosa:hasFeatureOfInterest ?l . 
	?l :hasID "London" . 
	?result sosa:value "True" .
}


