spring:
  application:
    name: TankValve
    
server:
  port: 8093
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka
  instance:
    metadataMap:
      connectionType: synchronous

eventBus:
  type: rabbitmq
  host: localhost
 
bpController:
  serviceUrl: http://localhost:8081